close all; clear; clc;
% @gsd: generate simulated data
% @gsm: generate simulated mixing matrix

debug = false;
addpath("/Users/xli77/Documents/MSIVA/scripts");
addpath("/Users/xli77/Documents/MSIVA/scripts/SIVA/");
addpath("/Users/xli77/Documents/MSIVA/scripts/toy_example/");
addpath(genpath('/Users/xli77/Documents/gift/GroupICATv4.0c'));

%% generate data
% simple K works with one or two subspaces
seed=7;
M_Tot=2;
N=3000;
Acond=3;
SNR=(1+999)/1; % high SNR

% define ground truth subspace structure used for data generation
% S1
S_ = {[1 2], [1 2]; ...
      [3 4 5], [3 4 5]; ...
      [6 7 8 9], [6 7 8 9]; ...
      [   10], [     ]; ...
      [   11], [     ]; ...
      [   12], [     ]; ...
      [     ], [   10]; ...
      [     ], [   11]; ...
      [     ], [   12]};

% S2
% S_ = {[1  2], [1  2]; ...
%       [3  4], [3  4]; ...
%       [5  6], [5  6]; ...
%       [7  8], [7  8]; ...
%       [9 10], [9 10]; ...
%       [  11], [    ]; ...
%       [  12], [    ]; ...
%       [    ], [  11]; ...
%       [    ], [  12]};

% S3
% S_ = {[1 2 3], [1 2 3]; ...
%       [4 5 6], [4 5 6]; ...
%       [7 8 9], [7 8 9]; ...
%       [   10], [     ]; ...
%       [   11], [     ]; ...
%       [   12], [     ]; ...
%       [     ], [   10]; ...
%       [     ], [   11]; ...
%       [     ], [   12]};

% S4
% S_ = {[1 2 3 4], [1 2 3 4]; ...
%       [5 6 7 8], [5 6 7 8]; ...
%       [  9], [   ]; ...
%       [ 10], [   ]; ...
%       [ 11], [   ]; ...
%       [ 12], [   ]; ...
%       [   ], [  9]; ...
%       [   ], [ 10]; ...
%       [   ], [ 11]; ...
%       [   ], [ 12]};

V = [20000,20000];

sim_misa = sim_MISA(seed,S_,V,N,Acond,SNR);
S = sim_misa.S;
M = sim_misa.M;
A = sim_misa.A;
Y = sim_misa.Y;
X = sim_misa.genX();

num_pc = 12;
num_iter = 10;

%% run optimization
% unimodal
[data1_um, aux_um, isi_um] = run_pca_ica(X, S, M, num_pc, num_iter, seed, Y, A);

% unimodal + multimodal
[data1_ummm, aux_ummm, isi_ummm] = run_mgpca_ica(X, S, M, num_pc, num_iter, seed, Y, A);

%% define test subspace structure
S1 = {[1  2], [1  2]; ...
      [3  4], [3  4]; ...
      [5  6], [5  6]; ...
      [7  8], [7  8]; ...
      [9 10], [9 10]; ...
      [  11], [    ]; ...
      [  12], [    ]; ...
      [    ], [  11]; ...
      [    ], [  12]};

% S1 = {[1 2 3], [1 2 3]; ...
%       [4 5 6], [4 5 6]; ...
%       [7 8 9], [7 8 9]; ...
%       [   10], [     ]; ...
%       [   11], [     ]; ...
%       [   12], [     ]; ...
%       [     ], [   10]; ...
%       [     ], [   11]; ...
%       [     ], [   12]};

% S1 = {[1 2 3 4], [1 2 3 4]; ...
%       [5 6 7 8], [5 6 7 8]; ...
%       [  9], [   ]; ...
%       [ 10], [   ]; ...
%       [ 11], [   ]; ...
%       [ 12], [   ]; ...
%       [   ], [  9]; ...
%       [   ], [ 10]; ...
%       [   ], [ 11]; ...
%       [   ], [ 12]};

% S1 = {[1 2], [1 2]; ...
%       [3 4 5], [3 4 5]; ...
%       [6 7 8 9], [6 7 8 9]; ...
%       [   10], [     ]; ...
%       [   11], [     ]; ...
%       [   12], [     ]; ...
%       [     ], [   10]; ...
%       [     ], [   11]; ...
%       [     ], [   12]};

K = size(S1,1);
S1_ = cell(size(M));

for mm = M
    if issparse(S1{mm})
        S1_{mm} = S1{mm};
    else
        ii = [];
        jj = [];
        for ii_ = 1:K
            jj_ = length(S1{ii_,mm});
            if jj_ ~= 0
                jj = [jj S1{ii_,mm}];
                ii = [ii ii_*ones(1,jj_)];
            end
        end
        S1_{mm} = sparse(ii, jj, ones(1,sum([S1{:,mm}] ~= 0)), ...
            K, sum([S1{:,mm}] ~= 0), sum([S1{:,mm}] ~= 0));
    end
end

%% run optimization
% unimodal
[data1_um_s1, aux_um_s1, isi_um_s1] = run_pca_ica(X, S1_, M, num_pc, num_iter, seed, Y, A);

% unimodal + multimodal
[data1_ummm_s1, aux_ummm_s1, isi_ummm_s1] = run_mgpca_ica(X, S1_, M, num_pc, num_iter, seed, Y, A);

%% save outputs
rootpath = '/Users/xli77/Documents/MSIVA/results/SIVA';

% outpath = 'subspace_struct_234111';
% save(fullfile(rootpath,outpath,'um.mat'),'data1_um','isi_um','aux_um');
% save(fullfile(rootpath,outpath,'ummm.mat'),'data1_ummm','isi_ummm','aux_ummm');

outpath = 'subspace_struct_234111_incorrect2222211';
save(fullfile(rootpath,outpath,'um.mat'),'data1_um_s1','isi_um_s1','aux_um_s1');
save(fullfile(rootpath,outpath,'ummm.mat'),'data1_ummm_s1','isi_ummm_s1','aux_ummm_s1');
